### ISSUE TITLE
asterisk notation

### ISSUE THREAD

**Issue by bes-internal** [tokuhirom/Router-Boom#11]
It may be worth changing the behavior of this
```
$router->add('/some/*', 'some');
```
from `.+` to `.*` ?

It would be more natural behavior

**Comment by tokuhirom** [comment]
Hm. It breaks backward compatibility. We can't change this behavior.

**Comment by bes-internal** [comment]
maybe `**` for this?

`/{foo}/**/{bar}` -> `/([^/]+)/.*/([^/]+)`

`/{foo}/**` -> `/([^/]+)/.*`
where match('/download/path/to/file.xml') 
=> `{controller...}, {'**' => 'path/to/file.xml'}`
where match('/download/') 
=> `{controller...}, {'**' => ''}`

**Comment by tokuhirom** [comment]
I can't understand your motivation. You can register both
```
$router->add('/some/*', 'some');
$router->add('/some/', 'some');
```

**Comment by bes-internal** [comment]
And one more if you need to rewrite the version with a slash
```
$router->add('/some', 'some'); => 301 to /some/
$router->add('/some/', 'some');
$router->add('/some/*', 'some'); => 301 to /some/
```
probably have to live with it... close
